/**
 * Normalized CI/CD Failure Schema.
 * Source: Blueflame-Spec-v3-ACAR.md Section 10.3
 *
 * Provider-agnostic schema — all failures (ADO, GitHub Actions)
 * normalize to this format before analysis.
 */

import type { FailureSource, FailureType, RemediationStatus } from "./enums.js";

/** Individual failed step within a pipeline */
export interface FailedStep {
	/** Step or task name */
	name: string;
	/** Process exit code */
	exitCode: number;
	/** Relevant log excerpt (truncated to 2000 chars) */
	logExcerpt: string;
	/** Duration in seconds */
	durationSeconds: number;
}

/** Per-test failure detail */
export interface TestFailureDetail {
	/** Test name or path */
	testName: string;
	/** Stack trace or error message */
	errorMessage: string;
	/** Duration in ms */
	durationMs: number;
}

/** Aggregated test results */
export interface TestResults {
	total: number;
	passed: number;
	failed: number;
	skipped: number;
	details: TestFailureDetail[];
}

/** Pipeline environment info */
export interface PipelineEnvironment {
	os: string;
	runtimeVersion: string;
	nodeVersion?: string;
}

/** The normalized failure record (Cosmos DB: failures container) */
export interface NormalizedFailure {
	/** Cosmos DB document ID */
	id: string;
	/** Unique failure ID: FAIL-{runId}-{seq} */
	failureId: string;
	/** Partition key — links to the Blueflame run that owns this pipeline */
	runId: string;
	/** Project reference */
	projectId: string;
	/** CI provider source */
	source: FailureSource;
	/** Provider pipeline/workflow ID */
	pipelineId: string;
	/** Build/run number from the CI provider */
	buildNumber: string;
	/** Category of failure */
	failureType: FailureType;
	/** Steps that failed */
	failedSteps: FailedStep[];
	/** Structured test results (if available) */
	testResults: TestResults | null;
	/** Pipeline environment */
	environment: PipelineEnvironment;
	/** Source branch that triggered the failure */
	branchRef: string;
	/** Commit SHA */
	commitSha: string;
	/** When the failure occurred */
	timestamp: string;
	/** URL to full pipeline log */
	rawLogUrl: string;
	/** TTL in seconds (default: 30 days = 2592000) */
	ttl: number;
}

/** Remediation task generated by the Fixer agent */
export interface RemediationTask {
	id: string;
	description: string;
	estimatedSigma: number;
	estimatedCost: number;
	agentRole: string;
}

/** Root cause analysis output from the Fixer agent */
export interface RootCauseAnalysis {
	/** Brief summary of what failed and why */
	summary: string;
	/** Detailed root cause explanation */
	rootCause: string;
	/** Confidence score 0-1 */
	confidence: number;
	/** Affected files */
	affectedFiles: string[];
	/** Suggested remediation tasks */
	remediationTasks: RemediationTask[];
}

/** A remediation record — links failure → analysis → new plan.lock */
export interface Remediation {
	/** Cosmos DB document ID */
	id: string;
	/** Unique remediation ID */
	remediationId: string;
	/** The failure being remediated */
	failureId: string;
	/** Blueflame run ID */
	runId: string;
	/** Project reference */
	projectId: string;
	/** Status lifecycle */
	status: RemediationStatus;
	/** Root cause analysis from Fixer agent */
	rootCause: RootCauseAnalysis | null;
	/** Lock ID of the remediation plan (new lock, not original) */
	remediationLockId: string | null;
	/** Link to original plan.lock that was running when failure occurred */
	parentLockId: string;
	/** ISO 8601 timestamps */
	createdAt: string;
	updatedAt: string;
}
