/**
 * Deployment service — post-run GitHub sync, CI monitoring, deploy trigger.
 *
 * Syncs task outputs to a GitHub repo as a PR, monitors CI, and triggers deploy.
 * Uses env vars GITHUB_OWNER / GITHUB_REPO for target repo.
 * Auth: GITHUB_TOKEN (PAT, simplest) or GitHub App credentials.
 * Each project maps to a folder: projects/{projectId}/
 * Branch per run: blueflame/{runId}
 */

import {
	type CommitResult,
	type PRResult,
	type WorkflowRun,
	commitFiles,
	createBranch,
	createOctokitClient,
	createPR,
	getWorkflowRuns,
	triggerWorkflow,
} from "@blueflame/github-app";
import type { DeploymentState } from "@blueflame/shared";
import type { Result } from "@blueflame/shared";
import { Octokit } from "octokit";

import { getRun, updateDeploymentState } from "./orchestrator.js";

/** GitHub config from env vars */
function getGitHubConfig() {
	const owner = process.env.GITHUB_OWNER;
	const repo = process.env.GITHUB_REPO;

	if (!owner || !repo) {
		return null;
	}

	const token = process.env.GITHUB_TOKEN;
	const appId = process.env.GITHUB_APP_ID;
	const privateKey = process.env.GITHUB_PRIVATE_KEY;
	const installationId = process.env.GITHUB_INSTALLATION_ID;

	return {
		owner,
		repo,
		token: token ?? "",
		appId: appId ?? "",
		privateKey: privateKey ?? "",
		installationId: Number(installationId) || 0,
	};
}

/** Create an authenticated Octokit — PAT if available, otherwise GitHub App */
async function getOctokit(
	config: NonNullable<ReturnType<typeof getGitHubConfig>>,
): Promise<Octokit> {
	if (config.token) {
		return new Octokit({ auth: config.token });
	}
	return createOctokitClient({
		owner: config.owner,
		repo: config.repo,
		appId: config.appId,
		privateKey: config.privateKey,
		installationId: config.installationId,
	});
}

/** Check if GitHub integration is configured */
export function isGitHubConfigured(): boolean {
	return getGitHubConfig() !== null;
}

/**
 * Sync task outputs to GitHub: create branch, commit files, open PR.
 */
export async function syncToGitHub(
	runId: string,
	commitMessage?: string,
): Promise<Result<{ branch: string; commit: CommitResult; pr: PRResult }>> {
	const config = getGitHubConfig();
	if (!config) {
		return {
			ok: false,
			error: new Error("GitHub integration not configured (GITHUB_OWNER / GITHUB_REPO missing)"),
		};
	}

	const run = await getRun(runId);
	if (!run) {
		return { ok: false, error: new Error(`Run not found: ${runId}`) };
	}

	// Update state to syncing
	updateDeploymentState(runId, { step: "syncing" });

	try {
		const octokit = await getOctokit(config);

		const branchName = `blueflame/${runId}`;

		// Collect all files from task outputs, prefixed with project folder
		const files: Array<{ path: string; content: string }> = [];
		for (const [, output] of Object.entries(run.taskOutputs)) {
			if (output.files) {
				for (const file of output.files) {
					files.push({
						path: `projects/${run.projectId}/${file.path}`,
						content: file.content,
					});
				}
			}
		}

		if (files.length === 0) {
			const state: DeploymentState = { step: "idle", error: "No files to commit" };
			updateDeploymentState(runId, state);
			return { ok: false, error: new Error("No files to commit — task outputs are empty") };
		}

		// Create branch
		await createBranch(octokit, {
			owner: config.owner,
			repo: config.repo,
			branch: branchName,
		});

		// Build commit message
		const message =
			commitMessage ??
			`feat: Blueflame run ${runId}\n\nGenerated by Blueflame AI software refinery.\nProject: ${run.projectId}\nTasks: ${Object.keys(run.taskOutputs).length}`;

		// Commit all files
		const commit = await commitFiles(octokit, {
			owner: config.owner,
			repo: config.repo,
			branch: branchName,
			message,
			files,
		});

		// Create PR
		const taskCount = Object.keys(run.taskOutputs).length;
		const pr = await createPR(octokit, {
			owner: config.owner,
			repo: config.repo,
			title: `[Blueflame] Run ${runId.slice(0, 8)} — ${taskCount} task${taskCount !== 1 ? "s" : ""}`,
			body: buildPRBody(run, files.length),
			head: branchName,
			labels: ["blueflame", "automated"],
		});

		const state: DeploymentState = {
			step: "synced",
			branchName,
			commitSha: commit.sha,
			prNumber: pr.number,
			prUrl: pr.htmlUrl,
		};
		updateDeploymentState(runId, state);

		return { ok: true, value: { branch: branchName, commit, pr } };
	} catch (err) {
		const errorMsg = err instanceof Error ? err.message : String(err);
		updateDeploymentState(runId, { step: "idle", error: errorMsg });
		return { ok: false, error: new Error(`GitHub sync failed: ${errorMsg}`) };
	}
}

/**
 * Get CI status for a run's branch.
 */
export async function getCIStatus(
	runId: string,
): Promise<Result<{ runs: WorkflowRun[]; step: DeploymentState["step"] }>> {
	const config = getGitHubConfig();
	if (!config) {
		return { ok: false, error: new Error("GitHub integration not configured") };
	}

	const run = await getRun(runId);
	if (!run?.deploymentState?.branchName) {
		return { ok: false, error: new Error("No branch found — run has not been synced to GitHub") };
	}

	try {
		const octokit = await getOctokit(config);

		const workflowRuns = await getWorkflowRuns(
			octokit,
			config.owner,
			config.repo,
			run.deploymentState.branchName,
		);

		// Determine step from latest workflow run
		let step: DeploymentState["step"] = run.deploymentState.step;
		const latest = workflowRuns[0];
		if (latest) {
			if (latest.status === "queued" || latest.status === "in_progress") {
				step = "ci_running";
			} else if (latest.conclusion === "success") {
				step = "ci_passed";
			} else if (latest.conclusion === "failure" || latest.conclusion === "cancelled") {
				step = "ci_failed";
			}

			updateDeploymentState(runId, {
				...run.deploymentState,
				step,
				workflowRunId: latest.id,
				workflowRunUrl: latest.htmlUrl,
			});
		}

		return { ok: true, value: { runs: workflowRuns, step } };
	} catch (err) {
		const errorMsg = err instanceof Error ? err.message : String(err);
		return { ok: false, error: new Error(`CI status check failed: ${errorMsg}`) };
	}
}

/**
 * Trigger deploy workflow for a run.
 */
export async function triggerDeploy(runId: string): Promise<Result<void>> {
	const config = getGitHubConfig();
	if (!config) {
		return { ok: false, error: new Error("GitHub integration not configured") };
	}

	const run = await getRun(runId);
	if (!run?.deploymentState) {
		return { ok: false, error: new Error("No deployment state — run has not been synced") };
	}

	if (run.deploymentState.step !== "ci_passed") {
		return {
			ok: false,
			error: new Error(
				`Cannot deploy — CI status is ${run.deploymentState.step}, expected ci_passed`,
			),
		};
	}

	try {
		const octokit = await getOctokit(config);

		await triggerWorkflow(octokit, {
			owner: config.owner,
			repo: config.repo,
			workflowId: "deploy.yml",
			ref: run.deploymentState.branchName ?? "main",
			inputs: {
				run_id: runId,
				project_id: run.projectId,
			},
		});

		updateDeploymentState(runId, {
			...run.deploymentState,
			step: "deployed",
			deployedAt: new Date().toISOString(),
		});

		return { ok: true, value: undefined };
	} catch (err) {
		const errorMsg = err instanceof Error ? err.message : String(err);
		updateDeploymentState(runId, {
			...run.deploymentState,
			step: "ci_passed",
			error: `Deploy failed: ${errorMsg}`,
		});
		return { ok: false, error: new Error(`Deploy trigger failed: ${errorMsg}`) };
	}
}

/**
 * Mark a run as deployed (for external deployments not triggered through the app).
 */
export async function markAsDeployed(runId: string): Promise<Result<void>> {
	const run = await getRun(runId);
	if (!run) {
		return { ok: false, error: new Error(`Run not found: ${runId}`) };
	}

	if (!run.deploymentState) {
		return { ok: false, error: new Error("No deployment state — run has not been synced") };
	}

	updateDeploymentState(runId, {
		...run.deploymentState,
		step: "deployed",
		deployedAt: new Date().toISOString(),
	});

	return { ok: true, value: undefined };
}

/** Build PR body markdown */
function buildPRBody(run: import("./orchestrator.js").RunState, fileCount: number): string {
	const taskSummaries = run.plan.tasks
		.map((t) => `- **${t.id}**: ${t.description} (${t.status})`)
		.join("\n");

	return `## Blueflame Automated PR

**Run ID**: \`${run.runId}\`
**Project**: \`${run.projectId}\`
**Files**: ${fileCount}

### Tasks
${taskSummaries}

---
Generated by [Blueflame](https://github.com/Blueflame) AI Software Refinery
`;
}
