export {
	type AgentSpanAttributes,
	type SpanEvent,
	type SpanTreeNode,
	type TraceSpan,
	SpanStatus,
	addSpanEvent,
	clearSpanStore,
	endSpan,
	getRunSpans,
	getSpanCount,
	getSpanTree,
	initTelemetry,
	isTelemetryEnabled,
	shutdownTelemetry,
	startAgentSpan,
	startRunTrace,
} from "./telemetry.js";
