"use client";

import { useState } from "react";

import type { TaskOutput } from "@/components/dashboard/FileTreePane";

interface GitHubSyncSectionProps {
	runId: string;
	taskOutputs: Record<string, TaskOutput>;
	onSync: (commitMessage: string) => Promise<void>;
}

export function GitHubSyncSection({ runId, taskOutputs, onSync }: GitHubSyncSectionProps) {
	const fileCount = Object.values(taskOutputs).reduce(
		(sum, output) => sum + (output.files?.length ?? 0),
		0,
	);
	const taskCount = Object.keys(taskOutputs).length;

	const defaultMessage = `feat: Blueflame run ${runId.slice(0, 8)}\n\nGenerated by Blueflame AI software refinery.\nTasks: ${taskCount}`;
	const [commitMessage, setCommitMessage] = useState(defaultMessage);
	const [syncing, setSyncing] = useState(false);
	const [error, setError] = useState<string | null>(null);

	const handleSync = async () => {
		setSyncing(true);
		setError(null);
		try {
			await onSync(commitMessage);
		} catch (err) {
			setError(err instanceof Error ? err.message : "Sync failed");
		} finally {
			setSyncing(false);
		}
	};

	return (
		<div className="space-y-3">
			<div className="flex items-center justify-between">
				<h3 className="text-sm font-semibold text-[--text-primary]">Commit & Push to GitHub</h3>
				<span className="text-xs text-[--text-muted]">
					{fileCount} file{fileCount !== 1 ? "s" : ""} from {taskCount} task
					{taskCount !== 1 ? "s" : ""}
				</span>
			</div>

			<div className="space-y-2">
				<label className="text-xs text-[--text-secondary]" htmlFor="commit-msg">
					Commit message
				</label>
				<textarea
					id="commit-msg"
					value={commitMessage}
					onChange={(e) => setCommitMessage(e.target.value)}
					rows={4}
					className="w-full rounded border border-[--border] bg-[--bg-primary] px-3 py-2 text-xs font-mono text-[--text-primary] focus:border-[--accent] focus:outline-none resize-none"
				/>
			</div>

			<div className="flex items-center gap-3">
				<span className="text-xs text-[--text-muted] font-mono">
					Branch: blueflame/{runId.slice(0, 8)}...
				</span>
			</div>

			{error && (
				<div className="rounded border border-red-500/30 bg-red-500/5 px-3 py-2">
					<p className="text-xs text-red-400">{error}</p>
				</div>
			)}

			<button
				type="button"
				onClick={handleSync}
				disabled={syncing || fileCount === 0}
				className="w-full rounded border border-emerald-500/50 bg-emerald-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-emerald-500 disabled:opacity-50 disabled:cursor-not-allowed"
			>
				{syncing ? (
					<span className="flex items-center justify-center gap-2">
						<span className="h-3 w-3 animate-spin rounded-full border-2 border-white/30 border-t-white" />
						Syncing to GitHub...
					</span>
				) : (
					`Commit & Push ${fileCount} file${fileCount !== 1 ? "s" : ""}`
				)}
			</button>
		</div>
	);
}
